name: 自动检测源代码更新并上传到阿里云

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: '直链'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230110/lineage-19.1-20230110-nightly-tissot-signed.zip'
#   schedule:
#    - cron: "0 * * * *"

env:
  a_URL: "https://sourceforge.net/projects/nippongsi/files/latest/download"
  mima: ${{ secrets.MIMA }}
  User: ${{ secrets.USER }}
  token: ${{ secrets.TOKEN }}
  
  

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: 设置阿里云CLI
      run: |
        pip install --upgrade simplejson
        pip install aliyunpan
        aliyunpan-cli
        echo "username: '$User'"  >  ~/.config/aliyunpan.yaml
        echo "password: '$mima'"  >>  ~/.config/aliyunpan.yaml
        echo "refresh_token: '$token'"  >  ~/.config/aliyunpan.yaml
        
        
    - name: 下载源代码文件
      run: |
        sudo mkdir /temp
        sudo curl -LJO https://sourceforge.net/projects/nippongsi/files/latest/download -o /temp
        
    - name: 上传源代码文件到阿里云盘
      run: |
        aliyunpan-cli upload /temp/* /nipponGSIs
