name: 自动检测源代码更新并上传到阿里云

on:
   workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'test'
        required: false
        default: ''
#  schedule:
#    - cron: "0 * * * *"

env:
  SOURCEFORGE_URL: "https://sourceforge.net/projects/nippongsi/files/latest/download"
  mima: ${{ secrets.MIMA }}
  User: ${{ secrets.USER }}

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: 设置阿里云CLI
      run: |
        pip install --upgrade simplejson
        pip install aliyunpan
        aliyunpan-cli
        echo "username: '$User'"  >  ~/.config/aliyunpan.yaml
        echo "password: '$mima'"  >>  ~/.config/aliyunpan.yaml
        
    - name: 下载源代码文件
      run: |
        wget ${{ env.SOURCEFORGE_URL }} -O fuck.zip
        
    - name: 上传源代码文件到阿里云盘
      run: |
        aliyunpan-cli upload fuck.zip
