name: 自动检测源代码更新并上传到阿里云

on:
  schedule:
    - cron: "0 * * * *"

env:
  SOURCEFORGE_URL: "https://sourceforge.net/projects/your-project/files/latest/download"
  ALIYUN_OSS_BUCKET: "my-oss-bucket"

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: 设置阿里云CLI
      run: |
        sudo apt-get pip
        sudo apt-get python3
        pip install aliyunpan
        aliyunpan-cli
        ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
        echo "refresh_token: '$ALIBABA_CLOUD_ACCESS_KEY_SECRET'"  >  ~/.config/aliyunpan.yaml
        
    - name: 下载源代码文件
      run: |
        FILE_NAME=$(wget -O - -q ${{ env.SOURCEFORGE_URL }} | awk -F '=' '{print $NF}')
        wget ${{ env.SOURCEFORGE_URL }} -O $FILE_NAME
        
    - name: 上传源代码文件到阿里云盘
      run: |
        aliyunpan-cli upload $FILE_NAME oss://${{ env.ALIYUN_OSS_BUCKET }}/$FILE_NAME
