name: 自动检测源代码更新并上传到阿里云

on:
  workflow_dispatch:
    inputs:
      GSI:
        description: 'SourceForge 直链'
        required: true
        default: ''
#   schedule:
#    - cron: "0 * * * *"

env:
  mima: ${{ secrets.MIMA }}
  User: ${{ secrets.USER }}
  token: ${{ secrets.TOKEN }}
  URL: https://sourceforge.net/projects/nippongsi/files/latest
  
  

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载源代码文件
      run: |
        sudo mkdir /temp
        sudo wget -P /temp $URL
        
    - name: 设置tianyiyun CLI
      run: |
        git clone https://github.com/Aruelius/cloud189.git cloud189
        cd cloud189
        pip install -r requirements.txt
        python main.py
        echo "'$User'"
        echo "'$mima'"
        cd /nipponGSIs
        
    - name: 上传源代码文件到阿里云盘
      run: |
        upload -f /temp/*
