name: 自动检测源代码更新并上传到阿里云

on:
   workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'test'
        required: false
        default: ''
#  schedule:
#    - cron: "0 * * * *"

env:
  SOURCEFORGE_URL: "https://sourceforge.net/projects/your-project/files/latest/download"
  ALIYUN_OSS_BUCKET: "nipponGSIs"
  mima: ${{ secrets.mima }}
  User: ${{ secrets.User }}
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: 设置阿里云CLI
      run: |
        sudo apt-get pip
        sudo apt-get python3
        pip install aliyunpan
        aliyunpan-cli
        echo "refresh_token: '$ALIBABA_CLOUD_ACCESS_KEY_SECRET'"  >  ~/.config/aliyunpan.yaml
        echo "username: '$User'"  >  ~/.config/aliyunpan.yaml
        echo "password: '$mima'"  >>  ~/.config/aliyunpan.yaml
        
    - name: 下载源代码文件
      run: |
        FILE_NAME=$(wget -O - -q ${{ env.SOURCEFORGE_URL }} | awk -F '=' '{print $NF}')
        wget ${{ env.SOURCEFORGE_URL }} -O $FILE_NAME
        
    - name: 上传源代码文件到阿里云盘
      run: |
        aliyunpan-cli upload $FILE_NAME /nipponGSIs
